[tool.mypy]
python_version = "3.11"
ignore_missing_imports = true
strict = false
plugins = ["sqlalchemy.ext.mypy.plugin"]
disable_error_code = ["import-untyped"]

[tool.ruff]
line-length = 100
target-version = "py311"
fix = true

[tool.ruff.lint]
select = ["E", "F", "W"]
ignore = ["E501", "E701", "E702", "E712", "F403", "F401"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"
docstring-code-format = true
docstring-code-line-length = "dynamic"
